"""Plain-language wording for every drug in the app.

The FDA facts (Rx vs OTC, RxNorm id, label link and date) are pulled from openFDA
by build_seed_from_openfda.py. The everyday-English wording below is written by
hand so nothing shown to a patient is raw label jargon, and the build script
then checks that the claims here really appear in the FDA label text.

Writing rules for this file:
  - Short, plain sentences. Explain any medical word you cannot avoid.
  - "What it is used for" and "what to ask about" are conversation starters for a
    clinician visit, never instructions to start, stop or change a medicine.
"""

from __future__ import annotations

# --------------------------------------------------------------------------
# Conditions: (name shown to people, aliases people might type,
#              default one-line "used for" text, words expected in the FDA label)
# Names are plain language on purpose (the "Simple" view shows them as-is).
# --------------------------------------------------------------------------
CONDITIONS = [
    ("Hypertension", ["high blood pressure", "htn", "essential hypertension", "hbp", "blood pressure"],
     "Lowers high blood pressure.", ["hypertension", "blood pressure"]),
    ("Type 2 diabetes mellitus", ["type 2 diabetes", "t2dm", "type II diabetes", "niddm", "diabetes mellitus type 2", "diabetes", "high blood sugar"],
     "Helps control blood sugar in type 2 diabetes.", ["diabetes", "glycemic"]),
    ("Seasonal allergic rhinitis", ["hay fever", "seasonal allergies", "allergic rhinitis", "pollen allergy", "allergies", "itchy eyes", "sneezing"],
     "Eases hay fever and allergy symptoms like sneezing, a runny nose and itchy eyes.", ["allerg", "hay fever", "rhinitis", "sneez"]),
    ("Gastroesophageal reflux disease", ["gerd", "acid reflux", "gord", "reflux", "heartburn"],
     "Treats acid reflux and heartburn (GERD).", ["gastroesophageal", "reflux", "heartburn", "gerd", "ulcer"]),
    ("Migraine", ["migraine headache", "migraines", "migraine disorder"],
     "Treats migraine.", ["migraine"]),
    ("High cholesterol", ["cholesterol", "hyperlipidemia", "dyslipidemia", "high ldl", "lipids"],
     "Lowers high cholesterol.", ["cholesterol", "lipid", "ldl"]),
    ("Depression", ["major depressive disorder", "mdd", "low mood", "feeling depressed"],
     "Treats depression.", ["depress"]),
    ("Anxiety", ["generalized anxiety disorder", "gad", "anxiety disorder", "panic disorder", "panic attacks"],
     "Treats anxiety.", ["anxiety", "panic"]),
    ("Asthma", ["wheezing", "asthma attacks", "reactive airway"],
     "Treats or helps prevent asthma symptoms.", ["asthma", "bronchospasm"]),
    ("Pain and fever", ["pain", "headache", "fever", "aches", "minor aches", "body aches", "toothache", "menstrual cramps"],
     "Eases minor aches and pains and lowers fever.", ["pain", "fever", "ache"]),
    ("Arthritis and inflammation", ["arthritis", "osteoarthritis", "rheumatoid arthritis", "joint pain", "inflammation", "sore joints"],
     "Eases pain and swelling from arthritis and other inflammation.", ["arthritis", "inflammat"]),
    ("Moderate to severe pain", ["severe pain", "strong pain", "surgery pain", "opioid"],
     "Treats pain that is strong enough to need a prescription pain reliever.", ["pain"]),
    ("Bacterial infections", ["infection", "antibiotic", "strep throat", "uti", "urinary tract infection", "sinus infection", "bronchitis", "pneumonia"],
     "Treats infections caused by bacteria. It does not work on viruses like colds or the flu.", ["infection"]),
    ("Underactive thyroid", ["hypothyroidism", "thyroid", "low thyroid"],
     "Replaces thyroid hormone when the thyroid does not make enough.", ["hypothyroid", "thyroid"]),
    ("Trouble sleeping", ["insomnia", "sleep problems", "cant sleep", "sleeplessness"],
     "Helps with trouble falling asleep.", ["insomnia", "sleep"]),
    ("Blood clots and stroke prevention", ["blood thinner", "atrial fibrillation", "afib", "dvt", "blood clot", "stroke", "heart attack prevention", "anticoagulant"],
     "Helps prevent harmful blood clots.", ["stroke", "thrombo", "clot", "embol", "myocardial", "heart attack", "cardiovascular", "atherothrombotic"]),
    ("Stuffy nose and congestion", ["nasal congestion", "stuffy nose", "congestion", "cold", "sinus pressure", "blocked nose"],
     "Relieves a stuffy nose.", ["nasal", "congestion", "sinus", "cold"]),
    ("Nausea and vomiting", ["nausea", "vomiting", "throwing up", "upset stomach"],
     "Prevents or treats nausea and vomiting.", ["nausea", "vomiting"]),
    ("Diarrhea", ["loose stools", "travelers diarrhea"],
     "Treats sudden loose stools (diarrhea).", ["diarrhea"]),
    ("Constipation", ["hard stools", "irregular bowel"],
     "Treats occasional constipation.", ["constipation", "laxative", "bowel"]),
    ("Swelling from fluid buildup", ["edema", "fluid retention", "water retention", "swollen legs"],
     "Removes extra fluid that causes swelling.", ["edema"]),
    ("Erectile dysfunction", ["ed", "impotence"],
     "Treats erectile dysfunction.", ["erectile"]),
    ("Gout", ["gout attacks", "high uric acid", "uric acid"],
     "Helps prevent gout attacks by lowering uric acid.", ["gout", "uric"]),
    ("Nerve pain", ["neuropathy", "nerve pain", "postherpetic neuralgia", "shingles pain"],
     "Treats nerve pain, such as pain that lingers after shingles.", ["neuralgia", "neuropath", "nerve"]),
    ("Muscle spasms", ["muscle spasm", "muscle pain", "back spasm", "muscle strain"],
     "Eases muscle spasms from strains and injuries.", ["muscle", "spasm"]),
]

# --------------------------------------------------------------------------
# Drug classes: shared plain wording. A drug can override any field.
#   name    - shown in the "Drug class" row (and matched by the overlap rules)
#   what    - one plain sentence on how it works
#   effects - common side effects, in everyday words
#   watch   - what to ask a clinician about ("Ask a clinician about" row)
# --------------------------------------------------------------------------
CLASSES = {
    "ace": dict(name="ACE inhibitor", what="Relaxes blood vessels so blood pressure comes down.",
                effects=["dry cough", "dizziness", "high potassium"],
                watch="Kidney and potassium blood tests. A dry cough that does not go away."),
    "arb": dict(name="Angiotensin II receptor blocker", what="Relaxes blood vessels so blood pressure comes down.",
                effects=["dizziness", "high potassium", "fatigue"],
                watch="Kidney and potassium blood tests."),
    "ccb": dict(name="Calcium channel blocker", what="Relaxes blood vessels and eases the workload on the heart.",
                effects=["ankle swelling", "flushing", "dizziness"],
                watch="Ankle swelling. Blood pressure readings at home."),
    "thiazide": dict(name="Thiazide diuretic", what="A water pill that helps the body get rid of extra salt and water.",
                     effects=["more urination", "low potassium", "sun sensitivity"],
                     watch="Blood tests for body salts (electrolytes). Staying hydrated and using sun protection."),
    "bb": dict(name="Beta blocker", what="Slows the heart and lowers blood pressure.",
               effects=["fatigue", "slow heart rate", "cold hands or feet"],
               watch="Heart rate and energy level. Tell your clinician if you have asthma."),
    "loop": dict(name="Loop diuretic", what="A strong water pill that removes extra fluid through urine.",
                 effects=["more urination", "dizziness", "low potassium"],
                 watch="Blood tests for body salts and kidneys. Signs of dehydration."),
    "mra": dict(name="Potassium-sparing diuretic", what="A water pill that keeps potassium in the body.",
                effects=["high potassium", "breast tenderness", "dizziness"],
                watch="Potassium and kidney blood tests."),
    "statin": dict(name="Statin (lowers cholesterol)", what="Slows how much cholesterol the liver makes.",
                   effects=["muscle aches", "headache", "stomach upset"],
                   watch="Muscle pain or weakness that is unexplained. Liver blood tests when your clinician asks for them."),
    "chol_abs": dict(name="Cholesterol absorption blocker", what="Blocks some of the cholesterol in food from being absorbed.",
                     effects=["diarrhea", "tiredness", "joint pain"],
                     watch="Muscle pain (especially if taken with a statin). Liver blood tests."),
    "biguanide": dict(name="Biguanide", what="Lowers blood sugar mainly by reducing the sugar the liver releases.",
                      effects=["stomach upset", "diarrhea", "metallic taste"],
                      watch="Kidney function and how your stomach handles it."),
    "sglt2": dict(name="SGLT2 inhibitor", what="Helps the kidneys remove extra sugar through urine.",
                  effects=["genital yeast infections", "more urination", "dehydration"],
                  watch="Staying hydrated. Genital infections. Nausea, vomiting or stomach pain that could signal ketones."),
    "glp1": dict(name="GLP-1 receptor agonist", what="Acts like a gut hormone that raises insulin after meals and lowers appetite.",
                 effects=["nausea", "vomiting", "decreased appetite"],
                 watch="Stomach symptoms, eating enough, and how to use the injection pen."),
    "sulfonylurea": dict(name="Sulfonylurea", what="Helps the pancreas release more insulin.",
                         effects=["low blood sugar", "weight gain", "dizziness"],
                         watch="Signs of low blood sugar and keeping regular meals."),
    "dpp4": dict(name="DPP-4 inhibitor", what="Helps the body make more insulin after meals.",
                 effects=["stuffy nose", "headache", "joint pain"],
                 watch="Unusual stomach pain and new joint pain."),
    "tzd": dict(name="Thiazolidinedione (insulin sensitizer)", what="Helps the body respond better to its own insulin.",
                effects=["swelling", "weight gain", "headache"],
                watch="Swelling, sudden weight gain or shortness of breath, which can be signs of heart failure."),
    "antihist2": dict(name="Second-generation antihistamine", what="Blocks histamine to ease sneezing, itching and a runny nose, usually with less drowsiness than older allergy pills.",
                      effects=["drowsiness", "dry mouth", "fatigue"],
                      watch="Whether it makes you sleepy, and other allergy medicines you take."),
    "antihist1": dict(name="First-generation antihistamine", what="Blocks histamine to dry up a runny nose and ease itching. It often causes sleepiness.",
                      effects=["drowsiness", "dry mouth", "dizziness"],
                      watch="Strong sleepiness, confusion in older adults, and other sedating medicines."),
    "ins": dict(name="Intranasal corticosteroid", what="Calms swelling inside the nose.",
                effects=["nosebleeds", "nasal irritation", "sore throat"],
                watch="Spray technique and nosebleeds."),
    "lt": dict(name="Leukotriene receptor antagonist", what="Blocks a body chemical that causes airway swelling and allergy symptoms.",
               effects=["headache", "stomach pain", "mood or behavior changes"],
               watch="Any mood or behavior changes, such as agitation or trouble sleeping. Tell your clinician right away."),
    "ppi": dict(name="Proton pump inhibitor", what="Lowers the amount of acid the stomach makes.",
                effects=["headache", "diarrhea", "abdominal pain"],
                watch="How long you need to stay on it and other acid medicines you take."),
    "h2": dict(name="H2 blocker", what="Lowers the amount of acid the stomach makes.",
               effects=["headache", "constipation", "diarrhea"],
               watch="Timing with meals and other medicines."),
    "triptan": dict(name="Triptan", what="Narrows swollen blood vessels in the head and blocks pain signals during a migraine.",
                    effects=["chest tightness", "tingling", "dizziness"],
                    watch="Any history of heart disease and how often you use it."),
    "gepant": dict(name="CGRP receptor antagonist (gepant)", what="Blocks a protein that plays a role in migraine pain.",
                   effects=["nausea", "sleepiness", "dry mouth"],
                   watch="How it fits with your other migraine medicines."),
    "ssri": dict(name="SSRI antidepressant", what="Raises serotonin, a brain chemical that helps steady mood.",
                 effects=["nausea", "trouble sleeping", "sexual side effects"],
                 watch="Mood changes or thoughts of self-harm, especially in the first weeks or after a dose change. Do not stop suddenly without asking."),
    "benzo": dict(name="Benzodiazepine (calming medicine)", what="Calms the nervous system, which eases anxiety.",
                  effects=["drowsiness", "dizziness", "poor coordination"],
                  watch="Sleepiness, memory problems and dependence. Never combine with opioids or alcohol unless a clinician says it is safe."),
    "nsaid": dict(name="NSAID (anti-inflammatory pain reliever)", what="Reduces pain, swelling and fever by blocking body chemicals that cause inflammation.",
                  effects=["stomach upset", "heartburn", "headache"],
                  watch="Black stools or stomach pain, blood pressure, kidney function, and use with blood thinners."),
    "anticoag": dict(name="Blood thinner (anticoagulant)", what="Makes the blood slower to clot.",
                     effects=["bleeding or easy bruising", "nosebleeds"],
                     watch="Any unusual bleeding, and telling every clinician you take it before surgery or dental work."),
    "antiplatelet": dict(name="Antiplatelet", what="Keeps blood cells called platelets from sticking together and forming clots.",
                         effects=["bleeding or easy bruising", "stomach upset", "rash"],
                         watch="Unusual bleeding, and other blood thinners on your list."),
}

# --------------------------------------------------------------------------
# Drugs. Fields:
#   name   - generic name shown in the app
#   cls    - key in CLASSES (or None with `klass` given)
#   route  - "how it is taken"
#   how    - how it is usually taken, in one short sentence
#   conds  - conditions it is used for: "Name" or ("Name", "custom text")
# Optional: what / effects / watch / klass (override the class wording),
#           fda (search word for the FDA label if different), fda_route,
#           fda_field + rx_otc (for a label openFDA cannot find by ingredient),
#           fda_use_check (an extra label search proving a use that few labels state),
#           rxnav (ingredient name to look up the RxNorm id, if different)
# --------------------------------------------------------------------------
DRUGS = [
    # ---- Blood pressure and heart ----
    dict(name="Lisinopril", cls="ace", route="oral", how="Once-daily tablet.", conds=["Hypertension"]),
    dict(name="Enalapril", cls="ace", route="oral", how="Tablet taken once or twice a day.", conds=["Hypertension"]),
    dict(name="Benazepril", cls="ace", route="oral", how="Once-daily tablet.", conds=["Hypertension"]),
    dict(name="Amlodipine", cls="ccb", route="oral", how="Once-daily tablet.", conds=["Hypertension"]),
    dict(name="Diltiazem", cls="ccb", route="oral", how="Tablet or capsule taken once or several times a day, depending on the type.",
         effects=["ankle swelling", "headache", "dizziness"], conds=["Hypertension"]),
    dict(name="Hydrochlorothiazide", cls="thiazide", route="oral", how="Once-daily tablet.",
         effects=["dizziness", "low potassium", "sun sensitivity"], conds=["Hypertension"]),
    dict(name="Chlorthalidone", cls="thiazide", route="oral", how="Once-daily tablet.", conds=["Hypertension"]),
    dict(name="Losartan", cls="arb", route="oral", how="Once-daily tablet.", conds=["Hypertension"]),
    dict(name="Valsartan", cls="arb", route="oral", how="Tablet taken once or twice a day.", conds=["Hypertension"]),
    dict(name="Metoprolol", cls="bb", route="oral", how="Tablet taken once or twice a day.", conds=["Hypertension"]),
    dict(name="Propranolol", cls="bb", route="oral", how="Tablet or capsule taken once or a few times a day.",
         effects=["fatigue", "slow heart rate", "vivid dreams"],
         conds=["Hypertension", ("Migraine", "Helps prevent migraine attacks.")]),
    dict(name="Atenolol", cls="bb", route="oral", how="Once-daily tablet.", conds=["Hypertension"]),
    dict(name="Carvedilol", cls="bb", route="oral", how="Tablet taken twice a day with food.",
         effects=["dizziness", "fatigue", "slow heart rate"], conds=["Hypertension"]),
    dict(name="Furosemide", cls="loop", route="oral", how="Tablet taken once or twice a day.",
         conds=["Swelling from fluid buildup", "Hypertension"]),
    dict(name="Spironolactone", cls="mra", route="oral", how="Once-daily tablet.",
         conds=["Swelling from fluid buildup", "Hypertension"]),

    # ---- Cholesterol ----
    dict(name="Atorvastatin", cls="statin", route="oral", how="Once-daily tablet.",
         effects=["joint or muscle pain", "diarrhea", "cold-like symptoms"],
         conds=[("High cholesterol", "Lowers cholesterol and the chance of a heart attack or stroke.")]),
    dict(name="Rosuvastatin", cls="statin", route="oral", how="Once-daily tablet.",
         conds=[("High cholesterol", "Lowers cholesterol and the chance of a heart attack or stroke.")]),
    dict(name="Simvastatin", cls="statin", route="oral", how="Once-daily tablet, usually taken in the evening.",
         conds=[("High cholesterol", "Lowers cholesterol and the chance of a heart attack or stroke.")]),
    dict(name="Pravastatin", cls="statin", route="oral", how="Once-daily tablet.",
         conds=[("High cholesterol", "Lowers cholesterol and the chance of a heart attack or stroke.")]),
    dict(name="Ezetimibe", cls="chol_abs", route="oral", how="Once-daily tablet.", conds=["High cholesterol"]),

    # ---- Diabetes ----
    dict(name="Metformin", cls="biguanide", route="oral", how="Tablet taken once or twice a day with meals.",
         conds=["Type 2 diabetes mellitus"]),
    dict(name="Empagliflozin", cls="sglt2", route="oral", how="Once-daily tablet.", conds=["Type 2 diabetes mellitus"]),
    dict(name="Semaglutide", cls="glp1", route="injection or oral (product-dependent)",
         how="Usually a once-weekly injection; a daily tablet form also exists.", conds=["Type 2 diabetes mellitus"]),
    dict(name="Glipizide", cls="sulfonylurea", route="oral", how="Tablet taken once or twice a day, usually before a meal.",
         effects=["low blood sugar", "dizziness", "nausea"],
         conds=["Type 2 diabetes mellitus"]),
    dict(name="Glimepiride", cls="sulfonylurea", route="oral", how="Once-daily tablet taken with breakfast.",
         conds=["Type 2 diabetes mellitus"]),
    dict(name="Sitagliptin", cls="dpp4", route="oral", how="Once-daily tablet.", conds=["Type 2 diabetes mellitus"]),
    dict(name="Pioglitazone", cls="tzd", route="oral", how="Once-daily tablet.", conds=["Type 2 diabetes mellitus"]),

    # ---- Allergies, asthma, cough and cold ----
    dict(name="Cetirizine", cls="antihist2", route="oral", how="Once-daily tablet.", conds=["Seasonal allergic rhinitis"]),
    dict(name="Loratadine", cls="antihist2", route="oral", how="Once-daily tablet.",
         effects=["drowsiness", "allergic reaction (rare)"],
         watch="Drowsiness is most likely if you take more than the label says. Any rash, swelling or trouble breathing needs medical help right away.",
         conds=["Seasonal allergic rhinitis"]),
    dict(name="Diphenhydramine", cls="antihist1", route="oral", how="Tablet, capsule or liquid taken every 4 to 6 hours as needed.",
         conds=["Seasonal allergic rhinitis",
                ("Trouble sleeping", "Helps with occasional sleeplessness. It can cause sleepiness the next day.")]),
    dict(name="Fluticasone (nasal)", cls="ins", route="nasal spray", how="Daily nasal spray.",
         fda="fluticasone", fda_route="NASAL", conds=["Seasonal allergic rhinitis"]),
    dict(name="Montelukast", cls="lt", route="oral", how="Once-daily tablet, usually taken in the evening.",
         conds=["Seasonal allergic rhinitis", ("Asthma", "Helps prevent asthma attacks. It is not a rescue medicine.")]),
    dict(name="Albuterol", klass="Rescue inhaler (opens the airways)", route="inhaler",
         how="Inhaled puffs taken as needed for wheezing or shortness of breath.",
         what="Quickly relaxes the muscles around the airways so it is easier to breathe.",
         effects=["shaky hands", "fast heartbeat", "nervousness"],
         watch="Needing your rescue inhaler more often than usual. Heart rate.",
         conds=[("Asthma", "Quickly relieves asthma symptoms like wheezing.")]),
    dict(name="Pseudoephedrine", klass="Decongestant", route="oral",
         how="Tablet or liquid taken every 4 to 6 hours as needed.",
         what="Shrinks swollen nasal passages so it is easier to breathe.",
         effects=["trouble sleeping", "nervousness", "fast heartbeat"],
         watch="High blood pressure or heart problems. It is sold from behind the pharmacy counter.",
         conds=[("Stuffy nose and congestion", "Relieves a stuffy nose from a cold or allergies.")]),

    # ---- Stomach and gut ----
    dict(name="Omeprazole", cls="ppi", route="oral", how="Once-daily capsule, often taken before a meal.",
         conds=["Gastroesophageal reflux disease"]),
    dict(name="Esomeprazole", cls="ppi", route="oral", how="Once-daily capsule.",
         effects=["headache", "diarrhea", "dry mouth"], watch="How long you need to stay on it.",
         conds=["Gastroesophageal reflux disease"]),
    dict(name="Pantoprazole", cls="ppi", route="oral", how="Once-daily tablet.",
         effects=["headache", "diarrhea", "nausea"], conds=["Gastroesophageal reflux disease"]),
    dict(name="Lansoprazole", cls="ppi", route="oral", how="Once-daily capsule, taken before a meal.",
         effects=["headache", "diarrhea", "abdominal pain"], conds=["Gastroesophageal reflux disease"]),
    dict(name="Famotidine", cls="h2", route="oral", how="Tablet taken once or twice a day, or as needed.",
         conds=["Gastroesophageal reflux disease"]),
    dict(name="Loperamide", klass="Anti-diarrheal", route="oral",
         how="Capsule or liquid taken after loose stools, up to a daily limit.",
         what="Slows the gut so stools become firmer.",
         effects=["constipation", "dizziness", "abdominal cramps"],
         watch="Never take more than the daily limit; very high doses can cause dangerous heart rhythm problems. See a clinician if diarrhea lasts more than 2 days or there is blood.",
         conds=["Diarrhea"]),
    dict(name="Ondansetron", klass="Anti-nausea medicine", route="oral",
         how="Tablet or dissolving tablet taken before treatment or as needed.",
         what="Blocks a signal in the gut and brain that triggers nausea.",
         effects=["headache", "constipation", "tiredness"],
         watch="Heart rhythm problems, and other medicines that raise serotonin.",
         conds=["Nausea and vomiting"]),
    dict(name="Polyethylene glycol", klass="Laxative (draws water into the bowel)", route="oral",
         rxnav="polyethylene glycol 3350",
         how="Powder mixed into a drink once a day.",
         what="Draws water into the bowel to soften stools.",
         effects=["bloating", "nausea", "loose stools"],
         watch="Diarrhea, or constipation that lasts more than a week.",
         conds=["Constipation"]),

    # ---- Migraine ----
    dict(name="Sumatriptan", cls="triptan", route="oral (other forms exist)", how="Taken as needed at the start of a migraine.",
         conds=[("Migraine", "Treats a migraine attack once it starts.")]),
    dict(name="Rizatriptan", cls="triptan", route="oral", how="Taken as needed at the start of a migraine.",
         effects=["drowsiness", "dizziness", "chest tightness"],
         conds=[("Migraine", "Treats a migraine attack once it starts.")]),
    dict(name="Ubrogepant", cls="gepant", route="oral", how="Taken as needed at the start of a migraine.",
         # openFDA does not index this label's ingredient field, so find it by product data instead.
         fda="ubrogepant", fda_field="spl_product_data_elements", rx_otc="Rx",
         conds=[("Migraine", "Treats a migraine attack once it starts.")]),
    dict(name="Topiramate", klass="Anticonvulsant (seizure medicine also used to prevent migraine)", route="oral",
         how="Daily tablet for prevention. It is not an as-needed medicine for a migraine attack.",
         what="Calms overactive nerve signals in the brain.",
         effects=["tingling", "word-finding difficulty", "appetite change"],
         watch="Mood, staying hydrated, kidney stones, and pregnancy plans.",
         conds=[("Migraine", "Helps prevent migraine attacks.")]),

    # ---- Blood clots ----
    dict(name="Warfarin", cls="anticoag", route="oral", how="Once-daily tablet at the same time each day. The dose is adjusted using blood tests.",
         effects=["bleeding or easy bruising", "bleeding gums"],
         watch="Regular blood tests (called INR) that show how well it is working, unusual bleeding, and how other medicines and foods rich in vitamin K change its effect.",
         conds=[("Blood clots and stroke prevention", "Helps prevent and treat harmful blood clots.")]),
    dict(name="Apixaban", cls="anticoag", route="oral", how="Tablet taken twice a day.",
         conds=[("Blood clots and stroke prevention", "Lowers the chance of stroke from an irregular heartbeat and treats blood clots.")]),
    dict(name="Rivaroxaban", cls="anticoag", route="oral", how="Tablet taken once or twice a day, depending on the reason.",
         conds=[("Blood clots and stroke prevention", "Lowers the chance of stroke from an irregular heartbeat and treats blood clots.")]),
    dict(name="Clopidogrel", cls="antiplatelet", route="oral", how="Once-daily tablet.",
         effects=["bleeding or easy bruising", "rash", "diarrhea"],
         conds=[("Blood clots and stroke prevention", "Lowers the chance of a heart attack or stroke in people with heart or artery disease.")]),
    dict(name="Aspirin", cls="antiplatelet", route="oral", fda_use_check='indications_and_usage:"heart attack"', how="Tablet taken as needed for pain, or once a day at a low dose for heart protection.",
         effects=["stomach upset", "heartburn", "easy bruising"],
         watch="Black stools or stomach pain, and other blood thinners on your list. Only take daily low-dose aspirin if a clinician recommends it.",
         conds=["Pain and fever",
                ("Blood clots and stroke prevention", "Low-dose aspirin can lower the chance of a heart attack or stroke in some people.")]),

    # ---- Thyroid and sleep ----
    dict(name="Levothyroxine", klass="Thyroid hormone replacement", route="oral",
         how="Once-daily tablet, usually taken on an empty stomach in the morning.",
         what="Replaces the thyroid hormone your body is not making enough of.",
         effects=["fast heartbeat", "shakiness", "trouble sleeping"],
         watch="Blood tests of thyroid levels, and taking it the same way every day. The side effects listed can mean the dose is too high.",
         conds=["Underactive thyroid"]),
    dict(name="Zolpidem", klass="Sleep medicine (sedative-hypnotic)", route="oral",
         how="Tablet taken right before bed, only when you can stay in bed for a full night.",
         what="Slows brain activity so it is easier to fall asleep.",
         effects=["drowsiness", "dizziness", "headache"],
         watch="Sleepwalking or other unusual sleep behavior, and drowsiness the next day.",
         conds=["Trouble sleeping"]),

    # ---- Mood and anxiety ----
    dict(name="Sertraline", cls="ssri", route="oral", how="Once-daily tablet or liquid.",
         conds=["Depression", ("Anxiety", "Treats anxiety disorders, including panic disorder.")]),
    dict(name="Escitalopram", cls="ssri", route="oral", how="Once-daily tablet.",
         conds=["Depression", ("Anxiety", "Treats generalized anxiety.")]),
    dict(name="Fluoxetine", cls="ssri", route="oral", how="Once-daily capsule or tablet.",
         conds=["Depression", ("Anxiety", "Treats panic disorder.")]),
    dict(name="Citalopram", cls="ssri", route="oral", how="Once-daily tablet.", conds=["Depression"]),
    dict(name="Bupropion", klass="Atypical antidepressant", route="oral", how="Tablet taken once or twice a day, depending on the type.",
         what="Affects the brain chemicals dopamine and norepinephrine to lift mood.",
         effects=["dry mouth", "trouble sleeping", "headache"],
         watch="Mood changes or thoughts of self-harm. The risk of seizures is higher at higher doses.",
         conds=["Depression"]),
    dict(name="Trazodone", klass="Atypical antidepressant", route="oral", how="Tablet taken once or twice a day, often in the evening.",
         what="Affects brain chemicals that help regulate mood.",
         effects=["drowsiness", "dizziness", "dry mouth"],
         watch="Mood changes or thoughts of self-harm, and sleepiness the next day.",
         conds=["Depression"]),
    dict(name="Buspirone", klass="Anti-anxiety medicine (buspirone type)", route="oral", how="Tablet taken two or three times a day.",
         what="Eases anxiety without making most people very sleepy. It takes a few weeks to work.",
         effects=["dizziness", "nausea", "headache"],
         watch="Dizziness, and alcohol or other sedating medicines.",
         conds=["Anxiety"]),
    dict(name="Alprazolam", cls="benzo", route="oral", how="Tablet taken as needed or a few times a day.",
         conds=[("Anxiety", "Treats anxiety and panic disorder.")]),
    dict(name="Lorazepam", cls="benzo", route="oral", how="Tablet taken as needed or a few times a day.",
         conds=[("Anxiety", "Treats anxiety.")]),

    # ---- Pain ----
    dict(name="Acetaminophen", klass="Pain and fever reducer (acetaminophen)", route="oral",
         how="Tablet, capsule or liquid taken every 4 to 6 hours as needed, up to a daily limit.",
         what="Eases pain and lowers fever.",
         effects=["liver damage if too much is taken", "rare skin rash"],
         watch="The total amount from all products, since many cold and pain products also contain acetaminophen. Alcohol use.",
         conds=["Pain and fever"]),
    dict(name="Ibuprofen", cls="nsaid", route="oral", how="Tablet or liquid taken every 4 to 8 hours with food as needed.",
         conds=["Pain and fever", "Arthritis and inflammation"]),
    dict(name="Naproxen", cls="nsaid", route="oral", how="Tablet taken every 8 to 12 hours with food.",
         conds=["Pain and fever", "Arthritis and inflammation"]),
    dict(name="Meloxicam", cls="nsaid", route="oral", how="Once-daily tablet.", conds=["Arthritis and inflammation"]),
    dict(name="Diclofenac", cls="nsaid", route="oral or applied to skin (product-dependent)", how="Tablet taken a few times a day, or a gel rubbed on sore joints.",
         conds=["Arthritis and inflammation", "Pain and fever"]),
    dict(name="Celecoxib", cls="nsaid", route="oral", how="Capsule taken once or twice a day.", conds=["Arthritis and inflammation"]),
    dict(name="Tramadol", klass="Opioid pain reliever", route="oral", how="Tablet taken every 4 to 6 hours as needed.",
         what="Changes how the brain senses pain.",
         effects=["nausea", "constipation", "dizziness"],
         watch="Sleepiness, slowed breathing and dependence. Never combine with benzodiazepines or alcohol unless a clinician says it is safe.",
         conds=["Moderate to severe pain"]),
    dict(name="Gabapentin", klass="Anticonvulsant (nerve pain and seizure medicine)", route="oral",
         how="Capsule or tablet taken up to three times a day.",
         what="Calms overactive nerve signals.",
         effects=["drowsiness", "dizziness", "swelling in the legs"],
         watch="Sleepiness and dizziness, especially with alcohol or opioid pain relievers.",
         conds=["Nerve pain"]),
    dict(name="Cyclobenzaprine", klass="Muscle relaxant", route="oral", how="Tablet taken up to three times a day, for short periods.",
         what="Eases muscle spasms by calming nerve signals to the muscles.",
         effects=["drowsiness", "dry mouth", "dizziness"],
         watch="Sleepiness, and use with other sedating medicines.",
         conds=["Muscle spasms"]),
    dict(name="Allopurinol", klass="Gout preventer (lowers uric acid)", route="oral", how="Once-daily tablet.",
         what="Lowers uric acid so gout attacks are less likely.",
         effects=["rash", "nausea", "gout flare-ups when first starting"],
         watch="A new rash (call your clinician right away), plus kidney function and uric acid blood tests.",
         conds=["Gout"]),

    # ---- Infections ----
    dict(name="Amoxicillin", klass="Penicillin antibiotic", route="oral", how="Capsule, tablet or liquid taken two or three times a day.",
         what="Kills bacteria or stops them from growing.",
         effects=["diarrhea", "nausea", "rash"],
         watch="Any past allergy to penicillin. A rash or trouble breathing could be an allergic reaction.",
         conds=[("Bacterial infections", "Treats infections caused by bacteria, such as ear, throat, chest and urinary infections. It does not work on viruses.")]),
    dict(name="Azithromycin", klass="Macrolide antibiotic", route="oral", how="Usually a short course of tablets, often once a day for a few days.",
         what="Stops bacteria from growing.",
         effects=["diarrhea", "nausea", "stomach pain"],
         watch="Heart rhythm problems, and other medicines you take.",
         conds=[("Bacterial infections", "Treats infections caused by bacteria, such as throat, chest and some skin infections. It does not work on viruses.")]),
    dict(name="Cephalexin", klass="Cephalosporin antibiotic", route="oral", how="Capsule or liquid taken a few times a day.",
         what="Kills bacteria or stops them from growing.",
         effects=["diarrhea", "nausea", "stomach upset"],
         watch="Any past allergy to penicillin or similar antibiotics.",
         conds=[("Bacterial infections", "Treats infections caused by bacteria, such as skin, ear and urinary infections. It does not work on viruses.")]),
    dict(name="Ciprofloxacin", klass="Fluoroquinolone antibiotic", route="oral", how="Tablet taken twice a day for a set number of days.",
         what="Kills bacteria by stopping them from copying their DNA.",
         effects=["nausea", "diarrhea", "dizziness"],
         watch="Tendon pain or swelling, tingling or numbness, and sun sensitivity. Call your clinician right away if any of these happen.",
         conds=["Bacterial infections"]),
    dict(name="Doxycycline", klass="Tetracycline antibiotic", route="oral", how="Capsule or tablet taken once or twice a day, with a full glass of water.",
         what="Stops bacteria from growing.",
         effects=["nausea", "sun sensitivity", "stomach upset"],
         watch="Sun protection, and spacing it apart from calcium, iron and antacids.",
         conds=["Bacterial infections"]),
    dict(name="Nitrofurantoin", klass="Urinary tract antibiotic", route="oral", how="Capsule or liquid taken with food, usually a few times a day.",
         what="Kills bacteria in the urinary tract.",
         effects=["nausea", "headache", "gas"],
         watch="Numbness or tingling, and any new cough or trouble breathing.",
         conds=[("Bacterial infections", "Treats urinary tract infections caused by bacteria.")]),
    dict(name="Metronidazole", klass="Nitroimidazole antibiotic", route="oral", how="Tablet taken two or three times a day.",
         what="Kills certain bacteria and parasites.",
         effects=["nausea", "metallic taste", "headache"],
         watch="Avoid alcohol while taking it and for a few days after. Numbness or tingling.",
         conds=["Bacterial infections"]),

    # ---- Men's health ----
    dict(name="Sildenafil", klass="PDE5 inhibitor (erectile dysfunction medicine)", route="oral",
         how="Tablet taken about an hour before sexual activity, no more than once a day.",
         what="Increases blood flow so an erection can happen with stimulation.",
         effects=["headache", "flushing", "upset stomach"],
         watch="Never combine with nitrate heart medicines, which can cause a dangerous drop in blood pressure. Sudden vision or hearing loss needs urgent care.",
         conds=["Erectile dysfunction"]),
    dict(name="Tadalafil", klass="PDE5 inhibitor (erectile dysfunction medicine)", route="oral",
         how="Tablet taken as needed, or once a day at a low dose.",
         what="Increases blood flow so an erection can happen with stimulation.",
         effects=["headache", "upset stomach", "back or muscle aches"],
         watch="Never combine with nitrate heart medicines, which can cause a dangerous drop in blood pressure. Sudden vision or hearing loss needs urgent care.",
         conds=["Erectile dysfunction"]),
]

# --------------------------------------------------------------------------
# Overlap rules (same shape the app already uses).
# --------------------------------------------------------------------------
COMBINATION_RULES = {
    "label": "General overlap flags — not a complete interaction checker, drug-interaction database, or advice about which medicines to stop",
    "duplicate_class_urgent": [
        "ACE inhibitor",
        "Angiotensin II receptor blocker",
        "Calcium channel blocker",
        "Thiazide diuretic",
        "Beta blocker",
        "Proton pump inhibitor",
        "H2 blocker",
        "Triptan",
        "CGRP receptor antagonist (gepant)",
        "Second-generation antihistamine",
        "Intranasal corticosteroid",
        "SGLT2 inhibitor",
        "GLP-1 receptor agonist",
        "Sulfonylurea",
        "DPP-4 inhibitor",
        "Biguanide",
        "Statin (lowers cholesterol)",
        "SSRI antidepressant",
        "NSAID (anti-inflammatory pain reliever)",
        "Benzodiazepine (calming medicine)",
        "Blood thinner (anticoagulant)",
    ],
    "pairs": [
        {
            "classes": ["ACE inhibitor", "Angiotensin II receptor blocker"],
            "severity": "urgent_seed",
            "title": "ACE inhibitor and ARB on the same list",
            "detail": "Using an ACE inhibitor together with an ARB is a combination clinicians often review closely. This flag is not a complete interaction check and is not an order to stop either medicine.",
        },
        {
            "classes": ["Proton pump inhibitor", "H2 blocker"],
            "severity": "discuss",
            "title": "Two acid-reducing classes on the same list",
            "detail": "A PPI and an H2 blocker sometimes appear together, and sometimes that overlap is worth a visit question. This is a discussion flag, not advice to drop one.",
        },
        {
            "classes": ["Triptan", "CGRP receptor antagonist (gepant)"],
            "severity": "discuss",
            "title": "More than one as-needed migraine class",
            "detail": "A triptan and a gepant on the same list is something people often double-check with a clinician (timing, how often each is used). This app cannot say they must or must not be combined.",
        },
    ],
}


# The first 23 drugs keep the ids they had in the original seed (ids come from row order), so
# medicine lists and compare picks people already saved in their browser still point at the
# same drugs. New drugs are added after them; do not reorder or remove these.
LEGACY_DRUG_ORDER = [
    "Lisinopril", "Amlodipine", "Hydrochlorothiazide", "Losartan", "Metoprolol", "Propranolol",
    "Metformin", "Empagliflozin", "Semaglutide", "Glipizide", "Sitagliptin", "Cetirizine",
    "Loratadine", "Fluticasone (nasal)", "Montelukast", "Omeprazole", "Pantoprazole",
    "Famotidine", "Esomeprazole", "Sumatriptan", "Rizatriptan", "Topiramate", "Ubrogepant",
]

# --------------------------------------------------------------------------
# Drug-interaction facts (used by build_seed_from_openfda.py)
#
# CLASS_LABEL_TERMS: words an FDA label uses when it talks about a whole class of
# medicines ("NSAIDs", "anticoagulants"), keyed by our drug class name. If drug A's label
# mentions one of these, drug B (in that class) gets a flag with the label sentence as proof.
#
# INTERACTION_NOTES: the plain-language explanation shown to people, written by hand.
# A flag is only shown when a real FDA label sentence backs it; these notes just explain it.
# "a" and "b" can hold class names or drug names; a rule matches in either direction.
# severity="urgent_seed" marks combinations clinicians treat as high-risk; it can only raise a flag, never lower it.
# --------------------------------------------------------------------------
CLASS_LABEL_TERMS = {
    "ACE inhibitor": ["ACE inhibitor", "ACE-inhibitor", "angiotensin converting enzyme inhibitor", "angiotensin-converting enzyme inhibitor"],
    "Angiotensin II receptor blocker": ["angiotensin receptor blocker", "angiotensin II receptor blocker", "ARB", "angiotensin II receptor antagonist"],
    "Thiazide diuretic": ["thiazide", "diuretics"],
    "Loop diuretic": ["loop diuretic", "diuretics"],
    "Potassium-sparing diuretic": ["potassium-sparing", "potassium sparing"],
    "Beta blocker": ["beta-blocker", "beta blocker", "beta-adrenergic blocking agent"],
    "Calcium channel blocker": ["calcium channel blocker", "calcium-channel blocker"],
    "Statin (lowers cholesterol)": ["statin", "HMG-CoA reductase inhibitor"],
    "SSRI antidepressant": ["SSRI", "selective serotonin reuptake inhibitor"],
    "Triptan": ["triptan", "5-HT1"],
    "Benzodiazepine (calming medicine)": ["benzodiazepine", "CNS depressant"],
    "Opioid pain reliever": ["opioid", "CNS depressant"],
    "Sleep medicine (sedative-hypnotic)": ["sedative", "hypnotic", "CNS depressant"],
    "Anticonvulsant (nerve pain and seizure medicine)": ["CNS depressant"],
    "Muscle relaxant": ["muscle relaxant", "CNS depressant"],
    "First-generation antihistamine": ["antihistamine", "CNS depressant"],
    "Second-generation antihistamine": ["antihistamine"],
    "NSAID (anti-inflammatory pain reliever)": ["NSAID", "nonsteroidal anti-inflammatory", "non-steroidal anti-inflammatory"],
    "Blood thinner (anticoagulant)": ["anticoagulant", "blood thinner"],
    "Antiplatelet": ["antiplatelet", "platelet aggregation inhibitor"],
    "Proton pump inhibitor": ["proton pump inhibitor", "PPI"],
    "H2 blocker": ["H2 blocker", "H2-receptor antagonist", "H2 receptor antagonist"],
    "Penicillin antibiotic": ["penicillin"],
    "Macrolide antibiotic": ["macrolide"],
    "Cephalosporin antibiotic": ["cephalosporin"],
    "Fluoroquinolone antibiotic": ["fluoroquinolone", "quinolone"],
    "Tetracycline antibiotic": ["tetracycline"],
    "Sulfonylurea": ["sulfonylurea"],
    "PDE5 inhibitor (erectile dysfunction medicine)": ["PDE5", "phosphodiesterase"],
    "Anti-nausea medicine": ["5-HT3"],
}

_ANTIBIOTICS = ["Penicillin antibiotic", "Macrolide antibiotic", "Cephalosporin antibiotic", "Fluoroquinolone antibiotic",
                "Tetracycline antibiotic", "Urinary tract antibiotic", "Nitroimidazole antibiotic"]
_SLEEPY = ["Benzodiazepine (calming medicine)", "Sleep medicine (sedative-hypnotic)",
           "Anticonvulsant (nerve pain and seizure medicine)", "Muscle relaxant", "First-generation antihistamine"]
_BP_PILLS = ["ACE inhibitor", "Angiotensin II receptor blocker"]
_WATER_PILLS = ["Thiazide diuretic", "Loop diuretic"]
_SEROTONIN = ["Triptan", "Opioid pain reliever", "Atypical antidepressant", "Anti-nausea medicine",
              "Anti-anxiety medicine (buspirone type)"]

INTERACTION_NOTES = [
    dict(a=["Opioid pain reliever"], b=_SLEEPY + ["Atypical antidepressant"], severity="urgent_seed",
         title="An opioid with another sleepy-making medicine",
         plain="Taken together they can cause extreme sleepiness and slowed breathing, which can be life-threatening."),
    dict(a=["Benzodiazepine (calming medicine)"], b=_SLEEPY,
         title="Two medicines that both cause sleepiness",
         plain="Both calm the nervous system. Together the sleepiness and slowed reactions can be stronger than expected."),
    dict(a=["SSRI antidepressant"], b=_SEROTONIN,
         title="Two medicines that both raise serotonin",
         plain="Too much serotonin can cause agitation, a fast heartbeat, fever and stiff muscles (serotonin syndrome). Clinicians watch this combination closely."),
    dict(a=["SSRI antidepressant"], b=["NSAID (anti-inflammatory pain reliever)"],
         title="An antidepressant with an anti-inflammatory pain reliever",
         plain="Together they can raise the chance of bleeding, especially in the stomach."),
    dict(a=["NSAID (anti-inflammatory pain reliever)"], b=["Blood thinner (anticoagulant)"], severity="urgent_seed",
         title="A pain reliever and a blood thinner",
         plain="Together they can raise the chance of serious bleeding, especially in the stomach."),
    dict(a=["NSAID (anti-inflammatory pain reliever)"], b=["Antiplatelet"], severity="urgent_seed",
         title="A pain reliever and a medicine that thins the blood",
         plain="Together they can raise the chance of stomach bleeding. Some pain relievers, like ibuprofen, can also weaken aspirin's heart protection."),
    dict(a=["Blood thinner (anticoagulant)"], b=["Antiplatelet", "SSRI antidepressant"],
         title="Two medicines that both raise bleeding risk",
         plain="Together they can make bleeding more likely. Tell your clinician about every medicine you take."),
    dict(a=["Blood thinner (anticoagulant)"], b=_ANTIBIOTICS,
         title="A blood thinner and an antibiotic",
         plain="Some antibiotics can strengthen a blood thinner like warfarin and raise bleeding risk. Extra blood tests are sometimes needed."),
    dict(a=_BP_PILLS, b=["Potassium-sparing diuretic"],
         title="Two medicines that can both raise potassium",
         plain="Too much potassium can affect the heart. Blood tests are used to keep watch."),
    dict(a=_BP_PILLS, b=_WATER_PILLS,
         title="A blood-pressure pill with a water pill",
         plain="Together they can lower blood pressure too much, especially when starting or after a dose change."),
    dict(a=["NSAID (anti-inflammatory pain reliever)"], b=_BP_PILLS + _WATER_PILLS + ["Potassium-sparing diuretic"],
         title="A pain reliever with a blood-pressure medicine",
         plain="Anti-inflammatory pain relievers can make blood-pressure medicines work less well and can strain the kidneys, especially together with a water pill."),
    dict(a=["Clopidogrel"], b=["Omeprazole", "Esomeprazole"], severity="urgent_seed",
         title="Clopidogrel with omeprazole or esomeprazole",
         plain="These stomach-acid medicines can make clopidogrel work less well, which matters for protection against heart attack and stroke."),
    dict(a=["Levothyroxine"], b=["Proton pump inhibitor", "H2 blocker"],
         title="Thyroid medicine with a stomach-acid medicine",
         plain="Stomach-acid medicines can lower how much thyroid medicine your body absorbs. Thyroid blood tests may need checking."),
    dict(a=["Simvastatin"], b=["Calcium channel blocker"],
         title="Simvastatin with a calcium channel blocker",
         plain="Some calcium channel blockers raise the level of simvastatin in the blood, which raises the chance of muscle problems."),
    dict(a=["Beta blocker"], b=["Calcium channel blocker"],
         title="A beta blocker with a calcium channel blocker",
         plain="Together they can slow the heart too much or lower blood pressure too far."),
]